version: '3.8'

services:
  db:
    image: postgres
    container_name: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: mysecretpassword
      POSTGRES_USER: postgres
    ports:
      - 54332:5432
    volumes:
      - ../db:/var/lib/postgresql/data
  
  app:
    build:
      context: ./
      dockerfile: Dockerfile
    container_name: app
    ports:
      - 8080:80
    working_dir: /var/www/html
    restart: always
    volumes:
      - ../src:/var/www/html
  